services:
  postgres:
    image: postgres:15-alpine
    container_name: optiflow_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - optiflow-network

  redis:
    image: redis:alpine
    container_name: optiflow_redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - optiflow-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: optiflow_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - optiflow-network
  
  auth-api:
    build:
      context: .
      args:
        APP_NAME: auth-api
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
    networks:
      - optiflow-network

  user-api:
    build:
      context: .
      args:
        APP_NAME: user-api
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - optiflow-network

  import-document:
    build:
      context: .
      args:
        APP_NAME: import-document
    ports:
      - '3002:3002'
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
      - JWT_SECRET=${JWT_SECRET}    
    depends_on:
      - rabbitmq
    networks:
      - optiflow-network

  dashboard-api:
    build:
      context: .
      args:
        APP_NAME: dashboard-api
    ports:
      - '3003:3003'
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    networks:
      - optiflow-network

  solver-process:
    build:
      context: .
      args:
        APP_NAME: solver-process
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - optiflow-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  optiflow-network:
    driver: bridge